name: "setup-frontend"

services:
  frontend:
    build:
      context: ./
      dockerfile: dockerfile
      args:
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
        NEXT_PUBLIC_FRONTEND_URL: ${NEXT_PUBLIC_FRONTEND_URL}
        NEXT_PUBLIC_DEFAULT_PAGE: ${NEXT_PUBLIC_DEFAULT_PAGE}
        NEXT_PUBLIC_DEFAULT_LIMIT: ${NEXT_PUBLIC_DEFAULT_LIMIT}
    ports:
      - "3000:3000"
    env_file: ./.env
    networks:
      - setup_network

networks:
  setup_network: # backend should start first to create this network
    name: setup_network
    external: true